# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1a85b2d
_src_path: .
author: Sir Meowsalots
cloud_service: Azure Function App
health_endpoint: health
language: python
open_source_license: MIT license
project_description: Kitties got claws...beware
project_name: KittenClaws
resources:
-   container: kittenclaws
    endpoint: kittenclaws
    name: KittenClaws
    operations:
    - list
    - get_by_id
    - create
    - update
    - delete

