[tool.poetry]
name = "KittenClaws"
version = "0.1.0"
description = "Kitties got claws...beware"
authors = ["Sir Meowsalots"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.14,<3.15"
pydantic = "^2.13.5"
pydantic-settings = "^2.15.0"

google-cloud-firestore = "^2.32.0"
functions-framework = "^3.10.2"

pytest-mock = "^3.15.1"
pytest-describe = "^3.2.0"

[tool.poetry.group.dev.dependencies]

pytest = "^9.1.1"
pytest-cov = "^7.1.0"
ruff = "^0.16.9"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term-missing --cov-fail-under=80"

[tool.coverage.run]
omit = ["*_test.py"]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E402", "E501", "W293"]

[tool.ruff.lint.per-file-ignores]
"blueprints/*" = ["F821", "F401"]
"main.py" = ["F401"]
"repositories/*" = ["F401"]
"*_test.py" = ["F401", "F841"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
