name: "setup-typescript"
description: "Composite action to setup the NodeJS and yarn environment."

inputs:
  node-version:
    required: false
    description: "The NodeJS version to use"
    default: "18.x"

runs:
  using: "composite"

  steps:
    - name: Setup Node ${{ inputs.node-version }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: corepack enable
      shell: bash

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: Kitten-Claws-typescript

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: Kitten-Claws-typescript

    - name: Unit tests
      uses: borales/actions-yarn@v4
      with:
        cmd: test:unit
        dir: Kitten-Claws-typescript
