name: Setup Cookiecutter Template
description: Composite action to setup the Cookiecutter template.

inputs:
  template-language:
    required: true
    description: Template language
  template-cloud-service:
    required: true
    description: Template cloud service

runs:
  using: "composite"

  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Cookiecutter
      run: pip install cookiecutter
      shell: bash

    - name: Install Cookiecutter Extensions
      run: pip install jinja2-strcase
      shell: bash

    - name: Create Cookiecutter Template
      run: |
        cookiecutter ./${{ inputs.template-language }} --no-input \
          project_name="KittenClaws" \
          project_description="Kitties got claws...beware" \
          project_slug="kitty_cats" \
          project_endpoint="kitties" \
          project_lower_camel_name="kittyCat" \
          project_class_name="KittyCat" \
          author="Sir Meowsalots" \
          cloud_service="${{ inputs.template-cloud-service }}" \
          open_source_license="MIT license"
      shell: bash
