name: "setup-env-nodejs"
description: "Composite action to setup the NodeJS and yarn environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.11"

runs:
  using: "composite"

  steps:
    - name: Setup Node ${{ inputs.node-version }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Cookiecutter
      run: pip install cookiecutter
      shell: bash

    - name: Install Cookiecutter Extensions
      run: $ pip install jinja2-strcase
      shell: bash

    - name: Create Cookiecutter Template
      run: |
        cookiecutter . --no-input \
          project_name="Kitten-Claws" \
          project_description="Kitties got claws...beware" \
          project_slug="kitty_cats" \
          project_endpoint="kitties" \
          project_lower_camel_name="kittyCat" \
          project_class_name="KittyCat" \
          author="Sir Meowsalots" \
          cloud_service="Azure Function App" \
          language="Typescript" \
          open_source_license="MIT license"
      shell: bash

    - run: corepack enable

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: Kitten-Claws-typescript

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: Kitten-Claws-typescript

    - name: Unit tests
      uses: borales/actions-yarn@v4
      with:
        cmd: test:unit
        dir: Kitten-Claws-typescript
