[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = "{{ cookiecutter.project_description }}"
authors = ["{{ cookiecutter.author }}"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
{% if cookiecutter.cloud_service == 'Azure Function App' -%}
azure-cosmos = "^4.15.0"
{%- endif %}
{% if cookiecutter.cloud_service == 'GCP Cloud Function' -%}
google-cloud-firestore = "^2.26.0"
functions-framework = "^3.10.0"
{%- endif %}
{% if cookiecutter.cloud_service == 'AWS Lambda' -%}
boto3 = "^1.42.0"
{%- endif %}
pytest-mock = "^3.14.0"
pytest-describe = "^3.0.0"

[tool.poetry.group.dev.dependencies]
{% if cookiecutter.cloud_service == 'Azure Function App' -%}
azure-functions = "2.0.0"
{%- endif %}
pytest = "^9.0.0"
pytest-cov = "^7.0.0"
pydantic = "^2.12.0"
ruff = "^0.15.0"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E402", "E501", "W293"]

[tool.ruff.lint.per-file-ignores]
"blueprints/*" = ["F821", "F401"]
"main.py" = ["F401"]
"repositories/*" = ["F401"]
"*_test.py" = ["F401", "F841"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
