skip-check:
  - CKV_AZURE_225
  - CKV_AZURE_212
  - CKV_AZURE_206
  - CKV_AZURE_100
  - CKV2_AZURE_1
  - CKV_AZURE_174
  - CKV2_AZURE_33
  - CKV_AZURE_59
  - CKV_AZURE_33
  - CKV2_AZURE_21
  - CKV_AZURE_140
  - CKV2_AZURE_40
  - CKV2_AZURE_41
