# expect: must be lowerCamelCase
resources:
  - name: "Cat"
    endpoint: "cats"
    container: "cats"
    operations: ["list", "get_by_id", "create", "update", "delete"]
    fields:
      - {name: name, type: string, required: true}
      - {name: "mood\n", type: string}
