# GitHub Build Pipeline
name: Cookiecutter API Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        python-version: ["3.10","3.11"]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Set up the environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: |
          cd "Test Project-python"
          poetry run pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

      # - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11 for Ubuntu
      #   uses: codecov/codecov-action@v3
      #   if: ${{ matrix.python-version == '3.11' }}
